
CONTROLLER_RATE: 70                       # rate in Hz

max_vel: 3                                # m/s
wp_threshold: 0.05                        # distance threshold at which we transition to next waypoint (m)
theta_threshold: rad(pi/8)                # robot theta threshold at which we transition to next waypoint (rad)

# controller params
controller_tf: {"num": [ 0.2, -0.3722704 ,  0.17246762], "den": [ 1., -1.97219114,  0.97238837]}

# localization filter params: AR1-142
positionFilterParams: {"Q": 0.8, "Q_d": 0.8}
thetaFilterParams: {"Q": 0.1, "Q_d": 0.1}
pos_measurement_std: 0.035                # position measurement standard deviation (m)
